# Generated by Django 3.0.2 on 2020-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no_optional',
            field=models.IntegerField(blank=True, null=True, verbose_name=15),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_owner_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no_optional',
            field=models.IntegerField(blank=True, null=True, verbose_name=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(blank=True, to='medicine_delivery.Medicine', verbose_name='list of medicines'),
        ),
    ]
