# Generated by Django 3.0.2 on 2020-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0002_auto_20200314_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no',
            field=models.BigIntegerField(verbose_name=15),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no_optional',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=15),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no',
            field=models.BigIntegerField(verbose_name=15),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no_optional',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=15),
        ),
    ]
