# Generated by Django 3.0.2 on 2020-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0003_auto_20200314_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalshop',
            options={'verbose_name': 'Medical Shop'},
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='shop_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
