# Generated by Django 3.0.2 on 2020-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0004_auto_20200314_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinemanufacturer',
            options={'verbose_name': 'Medical Manufacturer'},
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no',
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no_optional',
            field=models.BigIntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_pin_code',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no',
            field=models.BigIntegerField(max_length=15, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no_optional',
            field=models.BigIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
