# Generated by Django 3.0.2 on 2020-03-14 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0005_auto_20200314_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicine'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no_optional',
            field=models.BigIntegerField(blank=True, max_length=15, null=True, verbose_name='Optional Contact'),
        ),
    ]
