# Generated by Django 3.0.2 on 2020-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0006_auto_20200315_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_contact_no_optional',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no',
            field=models.BigIntegerField(verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='medicinemanufacturer',
            name='medicine_manufacturer_contact_no_optional',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Optional Contact'),
        ),
    ]
