# Generated by Django 3.0.2 on 2020-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_delivery', '0007_auto_20200315_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalshop',
            name='shop_pin_code',
            field=models.IntegerField(),
        ),
    ]
